# Generated by Django 4.2.14 on 2024-09-12 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=15)),
                ('year_of_build', models.DateField()),
                ('registration_plate', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
