# Generated by Django 4.2.14 on 2024-09-11 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=40)),
                ('date_joined_company', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('trucks', models.ManyToManyField(related_name='drivers', to='truck.truck')),
            ],
        ),
    ]
