# Generated by Django 4.2.14 on 2024-09-12 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTruckUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(max_length=20)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDayModel',
            fields=[
                ('worker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('load_carried', models.PositiveIntegerField()),
                ('fuel_consumption', models.PositiveIntegerField()),
                ('km_driven', models.PositiveIntegerField()),
                ('truck_used', models.ManyToManyField(through='working_shift.DriverTruckUsage', to='truck.truck')),
            ],
        ),
        migrations.AddField(
            model_name='drivertruckusage',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='working_shift.workingdaymodel'),
        ),
        migrations.AlterUniqueTogether(
            name='drivertruckusage',
            unique_together={('working_day', 'truck')},
        ),
    ]
