# Generated by Django 4.2.14 on 2024-09-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
        ('working_shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdaymodel',
            name='truck_used',
        ),
        migrations.DeleteModel(
            name='DriverTruckUsage',
        ),
        migrations.AddField(
            model_name='workingdaymodel',
            name='truck_used',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='truck.truck', to_field='registration_plate'),
        ),
    ]
