# Generated by Django 4.2.14 on 2024-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_shift', '0002_remove_workingdaymodel_truck_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdaymodel',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
