# Generated by Django 4.2.14 on 2024-09-14 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('working_shift', '0003_alter_workingdaymodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdaymodel',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
